@startuml Template

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!theme C4_united from https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/themes

title Template

System(system, "Sistema", "Descrição do sistema")

Boundary(boundary, "Nome", "Container ou Software System") {
    
    Container(Container1, "Coleta de Dados", "Coleta de Link e de alguns Metadados")

    Container(Container2, "Tratamento de dados","Trata os dados coletados em Python")

    Rel(system, Container1, "")
    Rel(system, Container2, "")
}

@enduml
